apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-hbmk
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0064-tenant/tkrw-pr712-0075-0064-app/devfile-sample-hbmk@sha256:c723caa1c56e9c1e4cbade3d156504f0c1961c69e8af8fd7ee426d7ce0bf36f7
        name: my-nodejs
        resources: {}
status: {}
